---
# --------------------------------

- name: 'Include Ubuntu tasks'
  ansible.builtin.include_tasks:
    file: '{{ ct_distro }}.yml'
  when: ct_distro == "ubuntu"
  tags: ["ct-gitlab"]

# --------------------------------
...
