---
# --------------------------------

- name: "Required packages"
  ansible.builtin.apt:
    name: "{{ gitlab_dependencies }}"
    state: present
  become: true
  tags: ["ct-gitlab"]

- name: "Optional install of Postfix"
  ansible.builtin.apt:
    name: ["postfix"]
    state: present
  when: gitlab_install_postfix
  become: true
  tags: ["ct-gitlab"]

- name: "Public key of Gitlab repo"
  ansible.builtin.apt_key:
    url: "{{ gitlab_gpg_key_url }}"
    state: "{{ gitlab_state }}"
  become: true
  tags: ["ct-gitlab"]

- name: "Gitlab package repo list"
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/{{ gitlab_repo_list }}
    group: root
    mode: "0644"
    owner: root
    src: repo.j2
  become: true
  tags: ["ct-gitlab"]

- name: "Install Gitlab package"
  ansible.builtin.apt:
    name: "{{ gitlab_edition }}"
    state: "{{ gitlab_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: ["ct-gitlab"]

- name: "Gitlab config file (no_log)"
  ansible.builtin.template:
    dest: /etc/gitlab/gitlab.rb
    group: root
    mode: "0600"
    owner: root
    src: gitlab.rb.j2
  no_log: true
  notify: HandlerReconfigure
  become: true
  tags: ["ct-gitlab"]

# --------------------------------
...
